version: "2"
pipeline:
  source:
    http:
      path: "/ingest"
  processor:
    - date:
        from_time_received: true
        destination: "@timestamp"
  sink:
    - opensearch:
        hosts: [ "https://<DOMAIN_ENDPOINT>" ]
        index: "spark"
        aws:
          sts_role_arn: "<INGESTION_ROLE_ARN>"
          region: "<AWS_REGION>"