# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

version: "2"
pipeline:
  source:
    http:
      path: "/ingest"
  processor:
    - date:
        from_time_received: true
        destination: "@timestamp"
  route:
    - task-metrics: '/metricsType == "taskMetrics"'
    - stage-agg-metrics: '/metricsType == "stageAggMetrics"'
  sink:
    - opensearch:
        hosts: [ "https://{domain_url}" ]
        index: "spark-stage-agg-metrics"
        aws_sts_role_arn: "{role_arn}"
        aws_region: "{region}"
        aws_sigv4: true
        routes:
          - stage-agg-metrics
    - opensearch:
        hosts: [ "https://{domain_url}" ]
        index: "spark-task-metrics"
        aws_sts_role_arn: "{role_arn}"
        aws_region: "{region}"
        aws_sigv4: true
        routes:
          - task-metrics