# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

version: "2"
pipeline:
  source:
    http:
      path: "/ingest"
  sink:
    - opensearch:
        hosts: [ "https://{domain_url}" ]
        index: "spark-logs"
        aws_sts_role_arn: "{role_arn}"
        aws_region: "{region}"
        aws_sigv4: true